CREATE DATABASE LABBD_TC3EX2_CLIENTE
GO
USE LABBD_TC3EX2_CLIENTE

CREATE TABLE Cliente(
cpf		CHAR(11)	NOT NULL,
nome	VARCHAR(100) NOT NULL,
email	VARCHAR(200) NOT NULL,
limiteCredito DECIMAL(7,2) NOT NULL,
dtNasc	DATE	NOT NULL
PRIMARY KEY (cpf)
)